In [1]:
import pandas as pd
df = pd.read_csv('../data/car_sales_cleaned1.csv')
df

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,Male,13500,Ford,Expedition,Auto,Black,26000
1,Male,1480000,Dodge,Durango,Auto,Black,19000
2,Male,1035000,Cadillac,Eldorado,Manual,Red,31500
3,Male,13500,Toyota,Celica,Manual,Pale White,14000
4,Male,1465000,Acura,TL,Auto,Red,24500
...,...,...,...,...,...,...,...
23901,Male,13500,Plymouth,Voyager,Manual,Red,12000
23902,Female,900000,Chevrolet,Prizm,Auto,Black,16000
23903,Male,705000,BMW,328i,Manual,Red,21000
23904,Male,13500,Chevrolet,Metro,Auto,Black,31000
23905,Male,1225000,Lexus,ES300,Auto,Pale White,27500

In [2]:
df = df.drop_duplicates() #removing duplicates
df.shape

(20358, 7)

In [3]:
df = df.dropna() # drop not available(with missing values)
df.shape

(20358, 7)

In [4]:
valuesColModel = df['Model'].unique()
valuesColModel

<StringArray>
[    'Expedition',        'Durango',       'Eldorado',         'Celica',
             'TL',       'Diamante',        'Corolla',         'Galant',
         'Malibu',         'Escort',
 ...
       'Firebird',            'V40',        'Montero', 'Town & Country',
             'SL',          'Alero',         'Mirage',        'Century',
          'RX300',         'Avalon']
Length: 154, dtype: str

In [5]:
dfProjection = df[['Annual Income', 'Price ($)']]
dfProjection

       Annual Income  Price ($)
0              13500      26000
1            1480000      19000
2            1035000      31500
3              13500      14000
4            1465000      24500
...              ...        ...
23898         530000      24000
23900         771000      19000
23902         900000      16000
23903         705000      21000
23905        1225000      27500

[20358 rows x 2 columns]

In [6]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
X = dfProjection[['Annual Income']]
y = dfProjection[['Price ($)']]
model.fit(X.values,y)
prediction = model.predict([[30000]])
prediction

array([61001])

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(X_train, y_train)
prediction = model.predict(X_test)
score = accuracy_score(y_test, prediction)
score

0.03388998035363458

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
import converter
model = DecisionTreeClassifier()
df_projection = df[['Company', 'Model']]
mapper = converter.columns_mapper(['Company', 'Model'],df_projection)
df_converted = converter.convert_x(df_projection,mapper)
X = df_converted[['Model']]
y = df_converted[['Company']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(X_train, y_train)
prediction = model.predict(X_test)
score = accuracy_score(y_test, prediction)
score

Enumerator !!! {'Toyota': 0, 'BMW': 1, 'Opel': 2}
columns_mapper!!! {'Company': {'Toyota': 0, 'Hundai': 1}, 'Model': {'Camry': 0, 'Corolla': 1, 'i10': 2}}
converted!!!             Company  Model
0        0      0
1        0      1
2        1      2

0.9987721021611002

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import converter
model = DecisionTreeClassifier()
y = df[['Gender']]
mapper = converter.columns_mapper(['Gender','Company', 'Model','Transmission','Color'],df)
df_converted = converter.convert_x(df,mapper)

In [10]:
#X = df_converted[['Annual Income','Company','Model','Transmission','Color','Price ($)']]
# X = df_converted[['Company','Model','Transmission']]
X = df_converted[['Color','Model','Transmission']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(X_train, y_train)
prediction = model.predict(X_test)
score = accuracy_score(y_test, prediction)
score

0.769155206286837

In [11]:
from sklearn.tree import DecisionTreeClassifier
import joblib
import converter

model = DecisionTreeClassifier()
y = df[['Gender']]
mapper = converter.columns_mapper(['Gender', 'Company', 'Model', 'Transmission', 'Color'], df)
df_converted = converter.convert_x(df, mapper)
X = df_converted[['Model','Transmission','Color']]
model.fit(X_train, y_train)
joblib.dump(model, '../models/car_gender_model.pkl')

['../models/car_gender_model.pkl']

In [12]:
import joblib
import converter

model = joblib.load('../models/car_gender_model.pkl')
mapper = converter.columns_mapper([ 'Model', 'Transmission', 'Color'], df)
prediction = model.predict([[mapper['Model']['Escort'],
                             mapper['Transmission']['Auto'],
                             mapper['Color']['Pale White']]])
prediction

C:\Users\Anna\miniconda3\envs\python-ai\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Male'], dtype=object)